### ISSUE TITLE
Using Notion instead of GitHub

### ISSUE THREAD

**Issue by ravgeetdhillon** [draftdev/jobs#10]
Hi Draft team,

Is it possible to use [Notion](https://notion.so) for creating job openings? We can then make those Notion pages public and link to them for the [draft.dev](http://draft.dev/) website.

**Comment by karllhughes** [comment]
@ravgeetdhillon we should probably use a "real" job board tool eventually, haha.

This was just my simple solution to get us started. I'm going to close this issue but put this on my long-term to-do list as I know GitHub isn't really the best place for job descriptions.
